### ISSUE TITLE
This project doesn't credit me

### ISSUE THREAD

**Issue by pdugan20** [bvellek/elected-officials-app#1]
Since this dope project was my idea I demand that I be credited somewhere in the code comments. Thanks dawg.

**Comment by Rosuav** [comment]
Did you write any of the code? Ideas aren't really creditable :)

**Comment by pdugan20** [comment]
This shit hasn't been fixed.

**Comment by Rosuav** [comment]
@pdugan20 How much did you contribute? How much work did you put into making this project a reality?

**Comment by pdugan20** [comment]
@Rosuav oh it's cool. Ben is my friend and I'm just giving him shit.
